from entpy import Pattern, Schema
from entpy.framework.fields.edge_field import EdgeField
from entpy.gencode.api_model_generator import generate as generate_api_model
from entpy.gencode.base_generator import generate as generate_base
from entpy.gencode.generated_content import GeneratedContent
from entpy.gencode.model_generator import generate as generate_model
from entpy.gencode.query_generator import generate as generate_query
from entpy.gencode.utils import ImportedObject, to_snake_case


def generate(
    pattern_class: type[Pattern],
    children_schema_classes: list[type[Schema]],
    vc: ImportedObject,
    threshold_to_stop_loading_ents_for_count: int,
) -> str:
    pattern = pattern_class()
    base_name = pattern_class.__name__.removesuffix("Pattern")

    model = generate_model(descriptor=pattern, base_name=base_name)
    api_model = generate_api_model(descriptor=pattern, base_name=base_name)

    child_types = _generate_child_types(children_schema_classes=children_schema_classes)

    base_content = generate_base(
        descriptor=pattern,
        base_name=base_name,
        vc=vc,
    )
    query_content = generate_query(
        descriptor=pattern,
        base_name=base_name,
        vc=vc,
        threshold_to_stop_loading_ents_for_count=threshold_to_stop_loading_ents_for_count,
    )

    mutator_content = _generate_mutator(
        pattern=pattern,
        base_name=base_name,
        children_schema_classes=children_schema_classes,
        vc=vc,
    )

    # Get the implementation to use for the example
    if not children_schema_classes:
        raise ValueError(f"No concrete implementation found for {base_name}")
    schema_class_name = pattern.get_example_subclass_name()
    if schema_class_name:
        example_base_name = schema_class_name
    else:
        schema_class = children_schema_classes[0]
        example_base_name = schema_class.__name__.removesuffix("Schema")

    # Generate the arguments for the gen_create function of the example
    example_arguments_definition = ""
    example_arguments_assignment = ""
    for field in pattern.get_all_fields():
        example_arguments_definition += f", {field.name}: {field.get_python_type()}"
        example_arguments_definition += (
            " | None = None" if field.nullable else " | Sentinel = NOTHING"
        )
        example_arguments_assignment += f", {field.name}={field.name}"

    # Make sure to import all the things!
    imports = (
        [
            str(vc),
            "from entpy import db",
            "from entpy.framework.errors import UnknownTypeError",
        ]
        + model.imports
        + api_model.imports
        + base_content.imports
        + query_content.imports
        + mutator_content.imports
    )

    imports = sorted(set(imports))  # Remove duplicates
    imports_code = "\n".join(imports)

    type_checking_imports = (
        model.type_checking_imports
        + api_model.type_checking_imports
        + base_content.type_checking_imports
        + query_content.type_checking_imports
        + mutator_content.type_checking_imports
    )
    if type_checking_imports:
        imports_code += "\n\nfrom typing import TYPE_CHECKING\n\n"
        imports_code += "if TYPE_CHECKING:\n"
        for imp in type_checking_imports:
            imports_code += f"    {imp}\n"

    return f"""####################
# Code generated by EntPy - do not modify manually!
####################

from __future__ import annotations
from abc import ABC, abstractmethod
from datetime import datetime
from functools import cache
from typing import Self, TYPE_CHECKING
from uuid import UUID

from sentinels import Sentinel, NOTHING  # type: ignore[import-untyped]

{imports_code}

if TYPE_CHECKING:
    from entpy import Ent

{model.code}

{api_model.code}

{base_content.code}

    @classmethod
    @cache
    def _get_child_type(cls, uuid_type: bytes) -> type[I{base_name}]:  {"# type: ignore[override]" if pattern.get_patterns() else ""}
        match uuid_type:
{child_types.code}
        raise UnknownTypeError(f"Unknown UUID type for I{base_name}: {{uuid_type.hex()}}")

{query_content.code}

{mutator_content.code}

class I{base_name}Example:
    @classmethod
    async def gen_create(
        cls, vc: {vc.name}, created_at: datetime | None = None{example_arguments_definition}
    ) -> I{base_name}:
        # TODO make sure we only use this in test mode

        from .{to_snake_case(example_base_name)} import {example_base_name}Example

        return await {example_base_name}Example.gen_create(vc=vc, created_at=created_at{example_arguments_assignment})
"""  # noqa: E501


def _generate_edges(pattern: Pattern) -> GeneratedContent:
    code = ""
    type_checking_imports = []
    for field in pattern.get_all_fields():
        if isinstance(field, EdgeField):
            or_not = " | None" if field.nullable else ""
            if field.edge_class != pattern.__class__:
                module = "." + to_snake_case(
                    field.edge_class.__name__.removesuffix("Schema").removesuffix(
                        "Pattern"
                    )
                )
                type_checking_imports.append(
                    f"from {module} import {field.get_edge_type()}"
                )
            code += f"""

    @abstractmethod
    async def gen_{field.original_name}(self) -> "{field.get_edge_type()}"{or_not}:
        pass
"""
    return GeneratedContent(
        imports=["from abc import abstractmethod"] if code else [],
        code=code,
        type_checking_imports=type_checking_imports,
    )


def _generate_child_types(
    children_schema_classes: list[type[Schema]],
) -> GeneratedContent:
    # Generate update method
    child_types = ""
    for schema_class in children_schema_classes:
        schema_base_name = schema_class.__name__.removesuffix("Schema")
        lower_schema = to_snake_case(schema_base_name)
        uuid_hex = "".join(f"\\x{b:02x}" for b in schema_class.get_uuid_type())
        child_types += f'            case b"{uuid_hex}":\n'
        child_types += (
            f"                from .{lower_schema} import {schema_base_name}\n"
        )
        child_types += f"                return {schema_base_name}\n"

    return GeneratedContent(code=child_types)


def _generate_mutator(
    pattern: Pattern,
    base_name: str,
    children_schema_classes: list[type[Schema]],
    vc: ImportedObject,
) -> GeneratedContent:
    # Generate the mutator class with update and delete methods
    mutator_methods = _generate_mutator_methods(
        base_name=base_name,
        children_schema_classes=children_schema_classes,
        vc=vc,
    )

    # Generate the abstract action classes
    update_action = _generate_update_action(base_name=base_name, vc=vc, pattern=pattern)
    delete_action = _generate_delete_action(base_name=base_name, vc=vc, pattern=pattern)

    # Add imports for parent pattern's mutator action classes if needed
    imports = []
    parent_patterns = pattern.get_patterns()
    if parent_patterns:
        for parent_pattern in parent_patterns:
            parent_base_name = parent_pattern.__class__.__name__.removesuffix("Pattern")
            parent_module = "." + to_snake_case(parent_base_name)
            imports.append(f"from {parent_module} import I{parent_base_name}MutatorUpdateAction")
            imports.append(f"from {parent_module} import I{parent_base_name}MutatorDeletionAction")

    code = f"""
class I{base_name}Mutator:
{mutator_methods}

{update_action}

{delete_action}
"""

    return GeneratedContent(code=code, imports=imports)


def _generate_delete_checks(
    children_schema_classes: list[type[Schema]], prefix: str
) -> str:
    delete_checks = ""
    for schema_class in children_schema_classes:
        schema_base_name = schema_class.__name__.removesuffix("Schema")
        lower_schema = to_snake_case(schema_base_name)
        delete_checks += f"""
        from .{lower_schema} import {schema_base_name}
        if isinstance(ent, {schema_base_name}):
            from .{lower_schema} import {schema_base_name}Mutator
            return {schema_base_name}Mutator.{prefix}_delete(vc, ent)
"""
    return delete_checks


def _generate_mutator_methods(
    base_name: str, children_schema_classes: list[type[Schema]], vc: ImportedObject
) -> str:
    # Generate update method
    update_checks = ""
    for schema_class in children_schema_classes:
        schema_base_name = schema_class.__name__.removesuffix("Schema")
        lower_schema = to_snake_case(schema_base_name)
        update_checks += f"""
        from .{lower_schema} import {schema_base_name}
        if isinstance(ent, {schema_base_name}):
            from .{lower_schema} import {schema_base_name}Mutator
            return {schema_base_name}Mutator.update(vc, ent)
"""

    # Generate delete methods
    soft_delete_checks = _generate_delete_checks(
        children_schema_classes=children_schema_classes, prefix="soft"
    )
    hard_delete_checks = _generate_delete_checks(
        children_schema_classes=children_schema_classes, prefix="hard"
    )

    return f"""
    @classmethod
    def update(
        cls, vc: {vc.name}, ent: I{base_name}
    ) -> I{base_name}MutatorUpdateAction:
{update_checks}
        raise ValueError(f"Unknown implementation for I{base_name}: {{type(ent)}}")

    @classmethod
    def hard_delete(
        cls, vc: {vc.name}, ent: I{base_name}
    ) -> I{base_name}MutatorDeletionAction:
{hard_delete_checks}
        raise ValueError(f"Unknown implementation for I{base_name}: {{type(ent)}}")

    @classmethod
    def soft_delete(
        cls, vc: {vc.name}, ent: I{base_name}
    ) -> I{base_name}MutatorDeletionAction:
{soft_delete_checks}
        raise ValueError(f"Unknown implementation for I{base_name}: {{type(ent)}}")
"""


def _generate_update_action(
    base_name: str, vc: ImportedObject, pattern: Pattern
) -> str:
    # Get mutable fields from the pattern (only the ones defined in this pattern)
    fields = pattern.get_fields()
    mutable_fields = list(filter(lambda f: not f.is_immutable, fields))

    # Build up the list of field attributes
    field_attributes = "\n".join(
        [
            f"        {field.name}: {field.get_python_type()}"
            + (" | None" if field.nullable else "")
            for field in mutable_fields
        ]
    )

    # Determine parent class for the mutator update action
    parent_patterns = pattern.get_patterns()
    if parent_patterns:
        # Inherit from the parent pattern's mutator update action
        parent_pattern = parent_patterns[0]  # Assume single inheritance for now
        parent_base_name = parent_pattern.__class__.__name__.removesuffix("Pattern")
        parent_class = f"I{parent_base_name}MutatorUpdateAction"
    else:
        parent_class = "ABC"

    return f"""
class I{base_name}MutatorUpdateAction({parent_class}):
    vc: {vc.name}
    ent: I{base_name}
    if TYPE_CHECKING:
{field_attributes or "        pass"}

    @abstractmethod
    async def gen_savex(self) -> I{base_name}:
        pass

    @abstractmethod
    async def gen_savex_or_403(self) -> I{base_name}:
        pass
"""


def _generate_delete_action(base_name: str, vc: ImportedObject, pattern: Pattern) -> str:
    # Determine parent class for the mutator deletion action
    parent_patterns = pattern.get_patterns()
    if parent_patterns:
        # Inherit from the parent pattern's mutator deletion action
        parent_pattern = parent_patterns[0]  # Assume single inheritance for now
        parent_base_name = parent_pattern.__class__.__name__.removesuffix("Pattern")
        parent_class = f"I{parent_base_name}MutatorDeletionAction"
    else:
        parent_class = "ABC"

    return f"""
class I{base_name}MutatorDeletionAction({parent_class}):
    vc: {vc.name}
    ent: I{base_name}

    @abstractmethod
    async def gen_save(self) -> None:
        pass

    @abstractmethod
    async def gen_save_or_403(self) -> None:
        pass
"""
