from entpy import Pattern, Schema
from entpy.framework.fields.edge_field import EdgeField
from entpy.gencode.api_model_generator import generate as generate_api_model
from entpy.gencode.base_generator import _generate_edge_gens, _generate_fields
from entpy.gencode.generated_content import GeneratedContent
from entpy.gencode.model_generator import generate as generate_model
from entpy.gencode.query_generator import generate as generate_query
from entpy.gencode.utils import ImportedObject, get_description, to_snake_case


def generate(
    pattern_class: type[Pattern],
    children_schema_classes: list[type[Schema]],
    vc: ImportedObject,
    threshold_to_stop_loading_ents_for_count: int,
) -> str:
    pattern = pattern_class()
    base_name = pattern_class.__name__.replace("Pattern", "")

    model = generate_model(descriptor=pattern, base_name=base_name)
    api_model = generate_api_model(descriptor=pattern, base_name=base_name)

    fields = _generate_fields(schema=pattern)
    edge_gens = _generate_edge_gens(schema=pattern)

    query_content = generate_query(
        descriptor=pattern,
        base_name=base_name,
        vc=vc,
        threshold_to_stop_loading_ents_for_count=threshold_to_stop_loading_ents_for_count,
    )

    mutator_content = _generate_mutator(
        pattern=pattern,
        base_name=base_name,
        children_schema_classes=children_schema_classes,
        vc=vc,
    )

    # Get the implementation to use for the example
    if not children_schema_classes:
        raise ValueError(f"No concrete implementation found for {base_name}")
    schema_class_name = pattern.get_example_subclass_name()
    if schema_class_name:
        example_base_name = schema_class_name
    else:
        schema_class = children_schema_classes[0]
        example_base_name = schema_class.__name__.replace("Schema", "")

    # Generate the arguments for the gen_create function of the example
    example_arguments_definition = ""
    example_arguments_assignment = ""
    for field in pattern.get_all_fields():
        example_arguments_definition += f", {field.name}: {field.get_python_type()}"
        example_arguments_definition += (
            " | None = None" if field.nullable else " | Sentinel = NOTHING"
        )
        example_arguments_assignment += f", {field.name}={field.name}"

    # Make sure to import all the things!
    imports = (
        [str(vc), "from entpy import db"]
        + model.imports
        + api_model.imports
        + fields.imports
        + query_content.imports
        + edge_gens.imports
        + mutator_content.imports
    )

    imports = sorted(set(imports))  # Remove duplicates
    imports_code = "\n".join(imports)

    type_checking_imports = (
        model.type_checking_imports
        + api_model.type_checking_imports
        + fields.type_checking_imports
        + edge_gens.type_checking_imports
        + query_content.type_checking_imports
        + mutator_content.type_checking_imports
    )
    if type_checking_imports:
        imports_code += "\n\nfrom typing import TYPE_CHECKING\n\n"
        imports_code += "if TYPE_CHECKING:\n"
        for imp in type_checking_imports:
            imports_code += f"    {imp}\n"

    return f"""####################
# Code generated by EntPy - do not modify manually!
####################

from __future__ import annotations
from abc import ABC, abstractmethod
from uuid import UUID
from entpy import Ent, ValidationError, validate_ent_id
from datetime import datetime
from sentinels import Sentinel, NOTHING  # type: ignore[import-untyped]
from typing import Self
{imports_code}

{model.code}

{api_model.code}

class I{base_name}(Ent):{get_description(pattern)}

    if TYPE_CHECKING:
{fields.code or "        pass"}

{edge_gens.code}

    @classmethod
    async def _genx_no_privacy_DO_NOT_USE(cls, vc: {vc.name}, ent_id: UUID | str, for_update: bool = False) -> I{base_name}:
        from .all_models import UUID_TO_ENT
        real_ent_id = validate_ent_id(ent_id)
        ent_type = UUID_TO_ENT[real_ent_id.bytes[6:8]]
        # Casting is ok here, the id always inherits I{base_name}
        return await cast(type[I{base_name}], ent_type)._genx_no_privacy_DO_NOT_USE(vc, ent_id, for_update)

    @classmethod
    async def gen(cls, vc: {vc.name}, ent_id: UUID | str, for_update: bool = False) -> I{base_name} | None:
        from .all_models import UUID_TO_ENT
        real_ent_id = validate_ent_id(ent_id)
        ent_type = UUID_TO_ENT[real_ent_id.bytes[6:8]]
        # Casting is ok here, the id always inherits I{base_name}
        return await cast(type[I{base_name}], ent_type).gen(vc, ent_id, for_update)

    @classmethod
    async def genx(cls, vc: {vc.name}, ent_id: UUID | str, for_update: bool = False) -> I{base_name}:
        ent = await cls.gen(vc, ent_id, for_update)
        if not ent:
            raise EntNotFoundError(f"No I{base_name} found for ID {{ent_id}}")
        return ent

    @classmethod
    def query_{to_snake_case(base_name)}(cls, vc: {vc.name}) -> I{base_name}Query:
        return I{base_name}Query(vc=vc)

{query_content.code}

{mutator_content.code}

class I{base_name}Example:
    @classmethod
    async def gen_create(
        cls, vc: {vc.name}, created_at: datetime | None = None{example_arguments_definition}
    ) -> I{base_name}:
        # TODO make sure we only use this in test mode

        from .{to_snake_case(example_base_name)} import {example_base_name}Example

        return await {example_base_name}Example.gen_create(vc=vc, created_at=created_at{example_arguments_assignment})
"""  # noqa: E501


def _generate_edges(pattern: Pattern) -> GeneratedContent:
    code = ""
    type_checking_imports = []
    for field in pattern.get_all_fields():
        if isinstance(field, EdgeField):
            or_not = " | None" if field.nullable else ""
            if field.edge_class != pattern.__class__:
                module = "." + to_snake_case(
                    field.edge_class.__name__.replace("Schema", "").replace(
                        "Pattern", ""
                    )
                )
                type_checking_imports.append(
                    f"from {module} import {field.get_edge_type()}"
                )
            code += f"""

    @abstractmethod
    async def gen_{field.original_name}(self) -> "{field.get_edge_type()}"{or_not}:
        pass
"""
    return GeneratedContent(
        imports=["from abc import abstractmethod"] if code else [],
        code=code,
        type_checking_imports=type_checking_imports,
    )


def _generate_mutator(
    pattern: Pattern,
    base_name: str,
    children_schema_classes: list[type[Schema]],
    vc: ImportedObject,
) -> GeneratedContent:
    # Generate the mutator class with update and delete methods
    mutator_methods = _generate_mutator_methods(
        base_name=base_name,
        children_schema_classes=children_schema_classes,
        vc=vc,
    )

    # Generate the abstract action classes
    update_action = _generate_update_action(base_name=base_name, vc=vc, pattern=pattern)
    delete_action = _generate_delete_action(base_name=base_name, vc=vc)

    code = f"""
class I{base_name}Mutator:
{mutator_methods}

{update_action}

{delete_action}
"""

    return GeneratedContent(code=code)


def _generate_delete_checks(
    children_schema_classes: list[type[Schema]], prefix: str
) -> str:
    delete_checks = ""
    for schema_class in children_schema_classes:
        schema_base_name = schema_class.__name__.replace("Schema", "")
        lower_schema = to_snake_case(schema_base_name)
        delete_checks += f"""
        from .{lower_schema} import {schema_base_name}
        if isinstance(ent, {schema_base_name}):
            from .{lower_schema} import {schema_base_name}Mutator
            return {schema_base_name}Mutator.{prefix}_delete(vc, ent)
"""
    return delete_checks


def _generate_mutator_methods(
    base_name: str, children_schema_classes: list[type[Schema]], vc: ImportedObject
) -> str:
    # Generate update method
    update_checks = ""
    for schema_class in children_schema_classes:
        schema_base_name = schema_class.__name__.replace("Schema", "")
        lower_schema = to_snake_case(schema_base_name)
        update_checks += f"""
        from .{lower_schema} import {schema_base_name}
        if isinstance(ent, {schema_base_name}):
            from .{lower_schema} import {schema_base_name}Mutator
            return {schema_base_name}Mutator.update(vc, ent)
"""

    # Generate delete methods
    soft_delete_checks = _generate_delete_checks(
        children_schema_classes=children_schema_classes, prefix="soft"
    )
    hard_delete_checks = _generate_delete_checks(
        children_schema_classes=children_schema_classes, prefix="hard"
    )

    return f"""
    @classmethod
    def update(
        cls, vc: {vc.name}, ent: I{base_name}
    ) -> I{base_name}MutatorUpdateAction:
{update_checks}
        raise ValueError(f"Unknown implementation for I{base_name}: {{type(ent)}}")

    @classmethod
    def hard_delete(
        cls, vc: {vc.name}, ent: I{base_name}
    ) -> I{base_name}MutatorDeletionAction:
{hard_delete_checks}
        raise ValueError(f"Unknown implementation for I{base_name}: {{type(ent)}}")

    @classmethod
    def soft_delete(
        cls, vc: {vc.name}, ent: I{base_name}
    ) -> I{base_name}MutatorDeletionAction:
{soft_delete_checks}
        raise ValueError(f"Unknown implementation for I{base_name}: {{type(ent)}}")
"""


def _generate_update_action(
    base_name: str, vc: ImportedObject, pattern: Pattern
) -> str:
    # Get mutable fields from the pattern
    fields = pattern.get_all_fields()
    mutable_fields = list(filter(lambda f: not f.is_immutable, fields))

    # Build up the list of field attributes
    field_attributes = "\n".join(
        [
            f"    {field.name}: {field.get_python_type()}"
            + (" | None" if field.nullable else "")
            for field in mutable_fields
        ]
    )

    return f"""
class I{base_name}MutatorUpdateAction(ABC):
    vc: {vc.name}
    ent: I{base_name}
{field_attributes}

    @abstractmethod
    async def gen_savex(self) -> I{base_name}:
        pass
"""


def _generate_delete_action(base_name: str, vc: ImportedObject) -> str:
    return f"""
class I{base_name}MutatorDeletionAction(ABC):
    vc: {vc.name}
    ent: I{base_name}

    @abstractmethod
    async def gen_save(self) -> None:
        pass
"""
