name: Python

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"
          cache-dependency-path: "uv.lock"

      - name: "Install uv"
        run: "pip install uv"

      - name: "Install dependencies"
        working-directory: entpy
        run: "uv sync --locked"

      - name: "Run ruff"
        working-directory: entpy
        run: "uv run ruff check ."

      - name: "Run ruff format"
        working-directory: entpy
        run: "uv run ruff format --check ."

      - name: "Run mypy"
        working-directory: entpy
        run: "uv run mypy ."

      - name: "Install dependencies (examples)"
        working-directory: examples
        run: "uv sync --locked"

      - name: "Check that generated code is up-to-date"
        working-directory: "examples"
        run: |
          uv run python run_gencode.py
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: Generated code is out of date. Please run 'uv run python run_gencode.py' and commit the changes."
            git status
            git diff
            exit 1
          fi

      - name: "Run ruff (examples)"
        working-directory: examples
        run: "uv run ruff check ."

      - name: "Run ruff format (examples)"
        working-directory: examples
        run: "uv run ruff format --check ."

      - name: "Run mypy (examples)"
        working-directory: examples
        run: "uv run mypy ."

      - name: "Run pytest (examples)"
        working-directory: examples
        run: "uv run pytest ."
